// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/LeeDark/go-web-labs/labs/layered-api/internal/app"
	"github.com/LeeDark/go-web-labs/labs/layered-api/internal/books"
	"github.com/LeeDark/go-web-labs/labs/layered-api/internal/http/handlers"
	"github.com/LeeDark/go-web-labs/labs/layered-api/internal/http/router"
	"net/http"
)

// Injectors from wire.go:

func initializeServer(addr string) (*http.Server, error) {
	memoryRepository := books.NewMemoryRepository()
	service := books.NewService(memoryRepository)
	logger := app.NewLogger()
	booksHandler := handlers.NewBooksHandler(service, logger)
	handler := router.New(booksHandler, logger)
	server := app.NewServer(addr, handler, logger)
	return server, nil
}
